[package]
name = "promkit"
version = "0.8.0"
authors = ["ynqa <un.pensiero.vano@gmail.com>"]
edition = "2021"
description = "A toolkit for building your own interactive command-line tools"
repository = "https://github.com/ynqa/promkit"
license = "MIT"
readme = "README.md"

[lib]
name = "promkit"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.95"
crossterm = { version = "0.28.1", features = ["use-dev-tty"] }
radix_trie = "0.2.1"
rayon = "1.10.0"
serde = { version = "1.0.217" }
serde_json = { version = "1.0.138", features = ["preserve_order"] }
unicode-width = "0.2.0"
